# Welcome to Jekyll!

locale: "en-US"
site_theme: "default"
title: "Haoren Mai's Homepage"
title_separator: "-"
name: &name "Haoren Mai"
description: &description "Haoren Mai's academic homepage"
url: "https://haorenmai.github.io"
baseurl: ""
repository: "haorenmai/haorenmai.github.io"

author:
  avatar: "5302787a3a804696a64350ef402af2a6.png"
  name: "Haoren Mai"
  bio: "Chinese."
  location: "Wuhan, China"
  employer: "Wuhan University"
  email: "houyanmak@whu.edu.cn"
  github: "haorenmai"
  orcid: "https://orcid.org/yourorcidurl"

publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

comments:
  provider: false

atom_feed:
  hide: false

analytics:
  provider: false

include:
  - .htaccess
  - _pages
  - files

exclude:
  - .github
  - node_modules
  - vendor
  - README
  - Gemfile*
  - package.json*
  - Rakefile
  - tmp

keep_files:
  - .git

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# ---- Only keep Publications ----
collections:
  publications:
    output: true
    permalink: /publications/:path/

# ---- Defaults: Keep only pages, posts, publications ----
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development

